### ISSUE TITLE
When clicking the TNT [IP BAN] in the gui it gives a console error

### ISSUE THREAD

**Issue by KahpotVanilla** [mgmadnesstv/PunishGUI-Issues#2]
Here is the following error:
```
07.11 17:19:31 [Server] ERROR Fatal error trying to convert PunishGUI v1.0.8:net/bghddevelopment/punishmentgui/menu/slots/Slot$1.class
07.11 17:19:31 [Server] INFO org.bukkit.plugin.AuthorNagException: No legacy enum constant for GRAY_STAINED_GLASS_PANE. Did you forget to define a modern (1.13+) api-version in your plugin.yml?
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.util.Commodore$1$1.visitFieldInsn(Commodore.java:327) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readCode(ClassReader.java:2444) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1514) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:744) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.libs.org.objectweb.asm.ClassReader.accept(ClassReader.java:424) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.util.Commodore.convert(Commodore.java:174) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.util.CraftMagicNumbers.processClass(CraftMagicNumbers.java:381) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:174) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
07.11 17:19:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
07.11 17:19:31 [Server] INFO at net.bghddevelopment.punishmentgui.menu.handler.CustomMenu$1.lambda$getSlots$0(CustomMenu.java:46) ~[PunishGUI.jar:?]
07.11 17:19:31 [Server] INFO at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
07.11 17:19:31 [Server] INFO at net.bghddevelopment.punishmentgui.menu.handler.CustomMenu$1.getSlots(CustomMenu.java:45) ~[PunishGUI.jar:?]
07.11 17:19:31 [Server] INFO at net.bghddevelopment.punishmentgui.menu.menu.AquaMenu.open(AquaMenu.java:39) ~[PunishGUI.jar:?]
07.11 17:19:31 [Server] INFO at net.bghddevelopment.punishmentgui.commands.PunishCommand.lambda$onCommand$0(PunishCommand.java:45) ~[PunishGUI.jar:?]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1564) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1279) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-373]
07.11 17:19:31 [Server] INFO at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

**Comment by mgmadnesstv** [comment]
This issues has nothing to do with my plugin.. You are using a different plugin!

**Comment by BGHDDevelopment** [comment]
@KahpotVanilla Please reach out to my support team regarding your issue. https://bghddevelopment.com/discord
In the future please make sure to use the support information listed on the specific plugin page.

**Comment by KahpotVanilla** [comment]
> This issues has nothing to do with my plugin.. You are using a different plugin!

Still, the IP-BAN command doesn't working

**Comment by mgmadnesstv** [comment]
Gain this is NOT an issue with MY plugin.

**Comment by KahpotVanilla** [comment]
> This issues has nothing to do with my plugin.. You are using a different plugin!

but I see your plugins name in there

**Comment by BGHDDevelopment** [comment]
This is my resource not his, please go to the Discord support server I linked above and post in #free-plugin-support

**Comment by KahpotVanilla** [comment]
> This is my resource not his, please go to the Discord support server I linked above and post in #free-plugin-support

oh xD alright then
